version: '3.7'

services:
  web:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: melhad

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
