SECRET_KEY: 'your_secret_key'
SQLALCHEMY_DATABASE_URI: 'sqlite:///app.db'
SQLALCHEMY_TRACK_MODIFICATIONS: False

STRIPE_PUBLIC_KEY: 'your_stripe_public_key'
STRIPE_SECRET_KEY: 'your_stripe_secret_key'

TWILIO_ACCOUNT_SID: 'your_twilio_account_sid'
TWILIO_AUTH_TOKEN: 'your_twilio_auth_token'
TWILIO_PHONE_NUMBER: 'your_twilio_phone_number'

AIRTEL_MONEY_API_KEY: 'your_airtel_money_api_key'
AIRTEL_MONEY_SECRET_KEY: 'your_airtel_money_secret_key'

PAYPAL_CLIENT_ID: 'your_paypal_client_id'
PAYPAL_CLIENT_SECRET: 'your_paypal_client_secret'

BANK_API_KEY: 'your_bank_api_key'
BANK_API_SECRET: 'your_bank_api_secret'

DEBUG: True
MAIL_SERVER: 'smtp.googlemail.com'
MAIL_PORT: 587
MAIL_USE_TLS: True
MAIL_USERNAME: 'your_email@example.com'
MAIL_PASSWORD: 'your_email_password'
ADMINS:
  - 'your-email@example.com'
